dream/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dreams.urls')),
    path('api/', include('dreams.api.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

dreams/api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.get_routes),
    path('rooms/', views.get_rooms),
    path('rooms/<str:pk>/', views.get_room)
]

dreams/urls.py
from django.urls import path

from . import views

app_name = 'dreams'
urlpatterns = [
    path('', views.home, name = 'home'),
    path('login/', views.login_page, name = 'login'),
    path('logout/', views.logout_user, name = 'logout'),
    path('register/', views.register_page, name = 'register'),
    path('profile/<str:pk>/', views.userProfile, name ='user-profile'),
    path('room/<str:pk>/', views.room, name = 'room'),
    path('create-room/', views.create_room, name = 'create-room'),
    path('update-room/<str:pk>/', views.update_room, name = 'update-room'),
    path('delete-room/<str:pk>/', views.delete_room, name = 'delete-room'),
    path('delete-message/<str:pk>/', views.delete_message, name = 'delete-message'),
    path('update-user/', views.update_user, name = 'update-user'),
    path('topics/', views.topics_page, name = 'topics'),
    path('activity/', views.activity_page, name = 'activity')
]

dreams/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class User(AbstractUser):
        name = models.CharField(max_length = 200, null = True)
        email = models.EmailField(unique = True, null = True)
        bio = models.TextField(null = True)

        avatar = models.ImageField(null = True, default = "avatar.svg")

        USERNAME_FIELD = 'email'
        REQUIRED_FIELDS = []


class Topic(models.Model):
    name = models.CharField(max_length = 200)

    def __str__(self):
        return self.name

class Room(models.Model):
    host = models.ForeignKey(User, on_delete = models.SET_NULL, null = True)
    topic = models.ForeignKey(Topic, on_delete = models.SET_NULL, null = True)
    name = models.CharField(max_length = 200)
    description = models.TextField(null = True, blank = True)
    participants = models.ManyToManyField(User, related_name = 'partcipants', blank = True)
    updated = models.DateTimeField(auto_now = True)
    created = models.DateTimeField(auto_now_add = True)

    class Meta:
        ordering = ['-updated', '-created']


    def __str__(self):
        return self.name

class Message(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    room = models.ForeignKey(Room, on_delete = models.CASCADE)
    body = models.TextField()
    updated = models.DateTimeField(auto_now = True)
    created = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return self.body[:50]


    class Meta:
        ordering = ['-updated', '-created']

dreams/forms.py
from django.forms import ModelForm
from .models import Room, User
from django.contrib.auth.forms import UserCreationForm

class MyUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['name', 'username', 'email', 'password1', 'password2']

class RoomForm(ModelForm):
    class Meta:
        model = Room
        fields = '__all__'
        exclude = ['host', 'participants']

class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['avatar', 'name', 'username', 'email', 'bio']

dreams/api/views.py
from django.http import JsonResponse
from rest_framework.decorators import api_view
from rest_framework.response import Response
from dreams.models import Room
from .serializers import RoomSerializer

@api_view(['GET'])
def get_routes(request):
    routes = [
        'GET /api', 
        'GET /api/rooms',
        'GET /api/rooms/:id'
    ]

    return Response(routes)

@api_view(['GET'])
def get_rooms(request):
    rooms = Room.objects.all()
    serializer = RoomSerializer(rooms, many = True)
    return Response(serializer.data)

@api_view(['GET'])
def get_room(request, pk):
    room = Room.objects.get(id = pk)
    serializer = RoomSerializer(room, many = False)
    return Response(serializer.data)

dreams/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.contrib.auth import authenticate, login, logout
from .models import Room, Topic, Message, User
from .forms import RoomForm, UserForm, MyUserCreationForm


# Create your views here.

def login_page(request):
    page = 'login'
    if request.user.is_authenticated:
        return redirect('dreams:home')

    if request.method == 'POST':
        email = request.POST.get('email').lower()
        password = request.POST.get('password')

        try:
            user = User.objects.get(email = email)
        except:
            messages.error(request, 'User does not exist') 

        user = authenticate(request, email = email, password=password)

        if user is not None:
            login(request, user)
            return redirect('dreams:home')
        else:
            messages.error(request, 'Username or password does not exist')

    context = {'page': page}
    return render(request, 'dreams/login_register.html', context)

def logout_user(request):
    logout(request)
    return redirect('dreams:home')

def register_page(request):
    form = MyUserCreationForm()

    if request.method == 'POST':
        form = MyUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit = False)
            user.username = user.username.lower()
            user.save()
            login(request, user)
            return redirect('dreams:home')
        else:
            messages.error(request, 'An error ocurred during registration')

    return render(request, 'dreams/login_register.html', {'form': form})

def home(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ''

    rooms = Room.objects.filter(
        Q(topic__name__icontains = q) |
        Q(name__icontains = q) |
        Q(description__icontains = q)
    )

    topics = Topic.objects.all()[:5]
    #room_count = rooms.count()
    room_messages = Message.objects.filter(Q(room__name__icontains = q))

    context = {'rooms': rooms, 'topics': topics, 'room_count': room_count, 'room_messages': room_messages}

    
    return render(request, 'dreams/home.html', context)

def room(request, pk):
    room = Room.objects.get(id = pk)
    room_messages = room.message_set.all()
    participants = room.participants.all()

    if request.method == 'POST':
        message = Message.objects.create(
            user = request.user,
            room = room,
            body = request.POST.get('body')
        )
        
        room.participants.add(request.user)

        return redirect('dreams:room', pk = room.id)

    context = {'room': room, 'room_messages': room_messages, 'participants': participants}
    
    return render(request, 'dreams/room.html', context)

def userProfile(request, pk):
    user = User.objects.get(id=pk)
    rooms = user.room_set.all()
    room_messages = user.message_set.all()
    topics = Topic.objects.all()
    context = {'user': user, 'rooms': rooms, 'room_messages': room_messages, 'topics': topics}
    return render(request, 'dreams/profile.html', context)

@login_required(login_url='dreams:login')
def create_room(request):
    form = RoomForm()
    topics = Topic.objects.all()

    if request.method == 'POST':
        topic_name = request.POST.get('topic')
        topic, created = Topic.objects.get_or_create(name = topic_name)
    
        Room.objects.create(
            host = request.user,
            topic = topic,
            name = request.POST.get('name'),
            description = request.POST.get('description')
        )

        return redirect('dreams:home') 

    context = {'form': form, 'topics': topics}
    return render(request, 'dreams/room_form.html', context)

@login_required(login_url='dreams:login')
def update_room(request, pk):
    room = Room.objects.get(id = pk)
    form = RoomForm(instance = room)
    topics = Topic.objects.all()

    if request.user != room.host:
        return HttpResponse('You are not allowed here')
    
    if request.method == 'POST':
        topic_name = request.POST.get('topic')
        topic, created = Topic.objects.get_or_create(name = topic_name)
        room.name = request.POST.get('name')     
        room.topic = topic
        room.description = request.POST.get('description')     
        room.save()

        return redirect('dreams:home')
    
    context = {'form': form, 'topics': topics, 'room': room}

    return render(request, 'dreams/room_form.html', context)

@login_required(login_url='dreams:login')
def delete_room(request, pk):
    room = Room.objects.get(id = pk)
    
    if request.user != room.host:
        return HttpResponse('You are not allowed here')
    
    if request.method == 'POST':
        room.delete()
        return redirect('dreams:home')

    return render(request, 'dreams/delete.html', {'obj': room})

@login_required(login_url='dreams:login')
def delete_message(request, pk):
    message = Message.objects.get(id = pk)
    
    if request.user != message.user:
        return HttpResponse('You are not allowed here')
    
    if request.method == 'POST':
        message.delete()
        return redirect('dreams:home')

    return render(request, 'dreams/delete.html', {'obj': message})

@login_required(login_url = 'dreams:login')
def update_user(request):
    user = request.user
    form = UserForm(instance = user)

    if request.method == 'POST':
        form = UserForm(request.POST, request.FILES, instance = user)
        if form.is_valid():
            form.save()
            return redirect('dreams:user-profile', pk = user.id)

    return render(request, 'dreams/update-user.html', {'form': form})

def topics_page(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ''
    topics = Topic.objects.filter(name__icontains = q)
    return render(request, 'dreams/topics.html', {'topics': topics})

def activity_page(request):
    room_messages = Message.objects.all()
    return render(request, 'dreams/activity.html', {})

dreams/templates/dreams/activity.html
{% extends 'dreams/main.html' %}   

{% block content %}

<main class="layout">
      <div class="container">
        <div class="layout__box">
          <div class="layout__boxHeader">
            <div class="layout__boxTitle">
							<a href="{% url 'dreams:home' %}">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>arrow-left</title>
                  <path
                    d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
                  ></path>
                </svg>
              </a>
              <h3>Recent Activities</h3>
            </div>
          </div>

          <div class="activities-page layout__body">
					{% for message in room_messages %}
          <div class="activities__box">
            <div class="activities__boxHeader roomListRoom__header">
							<a href="{% url 'dreams:user-profile' message.user.id %}" class="roomListRoom__author">
                <div class="avatar avatar--small">
                  <img src="https://randomuser.me/api/portraits/women/11.jpg" />
                </div>
                <p>
								@{{ message.user }}
								<span>{{ message.created|timesince }}</span>
                </p>
              </a>

							{% if request.user == message.user %}
              <div class="roomListRoom__actions">
								<a href="{% url 'dreams:delete-message' message.id %}">
                  <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                    <title>remove</title>
                    <path
                      d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
                    ></path>
                  </svg>
                </a>
              </div>
							{% endif %}
            </div>
            <div class="activities__boxContent">
							<p>replied to post “<a href="{% url 'dreams:room' message.room.id %}">{{ message.room.name }}</a>”</p>
              <div class="activities__boxRoomContent">
								{{ message.body }}
              </div>
            </div>
          </div>
					{% endfor %}

          </div>
        </div>
      </div>
    </main>

    <script src="script.js"></script>
{% endblock content %}

dreams/templates/dreams/activity_component.html
        <div class="activities">
          <div class="activities__header">
            <h2>Dreamers</h2>
          </div>
					{% for message in room_messages %}
          <div class="activities__box">
            <div class="activities__boxHeader roomListRoom__header">
							<a href="{% url 'dreams:user-profile' message.user.id %}" class="roomListRoom__author">
                <div class="avatar avatar--small">
									<img src={{ message.user.avatar.url }} />
                </div>
                <p>
								@{{ message.user }}
								<span>{{ message.created|timesince }}</span>
                </p>
              </a>

							{% if request.user == message.user %}
              <div class="roomListRoom__actions">
								<a href="{% url 'dreams:delete-message' message.id %}">
                  <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                    <title>remove</title>
                    <path
                      d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
                    ></path>
                  </svg>
                </a>
              </div>
							{% endif %}
            </div>
            <div class="activities__boxContent">
							<p>replied to post “<a style='color:black' href="{% url 'dreams:room' message.room.id %}">{{ message.room.name }}</a>”</p>
              <div class="activities__boxRoomContent">
								{{ message.body }}
              </div>
            </div>
          </div>
					{% endfor %}
        </div>

dreams/templates/dreams/delete_old.html
{% extends 'dreams/main.html' %}

{% block content %}

<form method="POST" action="">
	{% csrf_token %}
	<p>Are you sure you want to delete "{{ obj }}?"</p>
	<a href="{{ request.META.HTTP_REFERER }}">Go back</a>
	<input type='submit' value='confirm'>
</form>


{% endblock content %}

dreams/templates/dreams/home.html
{% extends 'dreams/main.html' %}
{% load static %}

{% block content %}

    <main class="layout layout--3">
      <div class="container">
        <!-- Topics Start -->
	{% include 'dreams/topics_component.html' %}
        <!-- Topics End -->

        <!-- Room List Start -->
        <div class="roomList">
          <div class="mobile-menu">
	      <form action="{% url 'dreams:home' %}" method="GET" class="header__search">
              <label>
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>search</title>
                  <path
                    d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
                  ></path>
                </svg>
                <input name="q" placeholder="Search for posts" />
              </label>
            </form>
            <div class="mobile-menuItems">
	      <a class="btn btn--main btn--pill" href="{% url 'dreams:topics' %}">Explore</a>
	      <a class="btn btn--main btn--pill" href="{% url 'dreams:activity' %}">Recent Activities</a>
            </div>
          </div>
          <div class="roomList__header">
            <div>
              <h2>Follow the white rabbit 🐇</h2>
	      {% if room_count == 1 %}
	      <p style='color: white;'>{{ rooms.count }} Dream that would await me...</p>
	      {% else %}
	      <p style='color: white;'>{{ rooms.count }} Dreams that would await me...</p>
	      {% endif %}
            </div>
	    <a class="btn btn--main" href="{% url 'dreams:create-room' %}">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>add</title>
                <path
                  d="M16.943 0.943h-1.885v14.115h-14.115v1.885h14.115v14.115h1.885v-14.115h14.115v-1.885h-14.115v-14.115z"
                ></path>
              </svg>
              Post
            </a>
          </div>
          {% include 'dreams/feed_component.html' %}
        </div>
        <!-- Room List End -->

        <!-- Activities Start -->
        {% include 'dreams/activity_component.html' %}        

        <!-- Activities End -->
      </div>
    </main>
{% endblock content %}

dreams/templates/dreams/navbar.html
{% load static %}
    <header class="header header--loggedIn">
      <div class="container">
				<a href="{% url 'dreams:home' %}" class="header__logo">
					<img src="{% static 'dreams/img/rabbit.png' %}"/>
          <h1>DreamScrape</h1>
        </a>
				<form class="header__search" method='GET' action="{% url 'dreams:home' %}">
          <label style='background-color:white'>
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>search</title>
              <path
                d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
              ></path>
            </svg>
            <input style='color:black'name='q' placeholder="Explore..." />
          </label>
        </form>
        <nav class="header__menu">
					{% if request.user.is_authenticated %}					
          <div class="header__user">
		  <a href="{% url 'dreams:user-profile' user.id %}">
              <div class="avatar avatar--medium active">
		      <img src="{{ request.user.avatar.url }}" />
              </div>
							<p>{{ request.user.username }} <span>@{{ request.user.username }}</span></p>
            </a>
            <button class="dropdown-button">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>chevron-down</title>
                <path d="M16 21l-13-13h-3l16 16 16-16h-3l-13 13z"></path>
              </svg>
            </button>
          </div>
         	{% else %} 
					<!-- Not Logged In -->
					<a href="{% url 'dreams:login' %}">
						<img src="{% static 'dreams/img/avatar.svg' %}" />
            <p>Login</p>
          </a>
					{% endif %}
          <div class="dropdown-menu">
		  <a href="{% url 'dreams:update-user' %}" class="dropdown-link"
              ><svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>tools</title>
                <path
                  d="M27.465 32c-1.211 0-2.35-0.471-3.207-1.328l-9.392-9.391c-2.369 0.898-4.898 0.951-7.355 0.15-3.274-1.074-5.869-3.67-6.943-6.942-0.879-2.682-0.734-5.45 0.419-8.004 0.135-0.299 0.408-0.512 0.731-0.572 0.32-0.051 0.654 0.045 0.887 0.277l5.394 5.395 3.586-3.586-5.394-5.395c-0.232-0.232-0.336-0.564-0.276-0.887s0.272-0.596 0.572-0.732c2.552-1.152 5.318-1.295 8.001-0.418 3.274 1.074 5.869 3.67 6.943 6.942 0.806 2.457 0.752 4.987-0.15 7.358l9.392 9.391c0.844 0.842 1.328 2.012 1.328 3.207-0 2.5-2.034 4.535-4.535 4.535zM15.101 19.102c0.26 0 0.516 0.102 0.707 0.293l9.864 9.863c0.479 0.479 1.116 0.742 1.793 0.742 1.398 0 2.535-1.137 2.535-2.535 0-0.668-0.27-1.322-0.742-1.793l-9.864-9.863c-0.294-0.295-0.376-0.74-0.204-1.119 0.943-2.090 1.061-4.357 0.341-6.555-0.863-2.631-3.034-4.801-5.665-5.666-1.713-0.561-3.468-0.609-5.145-0.164l4.986 4.988c0.391 0.391 0.391 1.023 0 1.414l-5 5c-0.188 0.188-0.441 0.293-0.707 0.293s-0.52-0.105-0.707-0.293l-4.987-4.988c-0.45 1.682-0.397 3.436 0.164 5.146 0.863 2.631 3.034 4.801 5.665 5.666 2.2 0.721 4.466 0.604 6.555-0.342 0.132-0.059 0.271-0.088 0.411-0.088z"
                ></path>
              </svg>
              Settings</a
            >
						<a href="{% url 'dreams:logout' %}" class="dropdown-link"
              ><svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>sign-out</title>
                <path
                  d="M3 0h22c0.553 0 1 0 1 0.553l-0 3.447h-2v-2h-20v28h20v-2h2l0 3.447c0 0.553-0.447 0.553-1 0.553h-22c-0.553 0-1-0.447-1-1v-30c0-0.553 0.447-1 1-1z"
                ></path>
                <path
                  d="M21.879 21.293l1.414 1.414 6.707-6.707-6.707-6.707-1.414 1.414 4.293 4.293h-14.172v2h14.172l-4.293 4.293z"
                ></path>
              </svg>
              Logout</a
            >
          </div>
        </nav>
      </div>
    </header>

dreams/templates/dreams/room.html
{% extends 'dreams/main.html' %}    

{% block content %}

<main class="profile-page layout layout--2">
      <div class="container">
        <!-- Room Start -->
        <div class="room" style='background-color:white;'>
          <div class="room__top" style='background-color:black'>
            <div class="room__topLeft">
							<a href="{% url 'dreams:home' %}">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>arrow-left</title>
                  <path
                    d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
                  ></path>
                </svg>
              </a>
              <h3>Dreams</h3>
            </div>
						
						{% if room.host == request.user %}
            <div class="room__topRight" style=''>
							<a href="{% url 'dreams:update-room' room.id %}">
                <svg
                  enable-background="new 0 0 24 24"
                  height="32"
                  viewBox="0 0 24 24"
                  width="32"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <title>edit</title>
                  <g>
                    <path d="m23.5 22h-15c-.276 0-.5-.224-.5-.5s.224-.5.5-.5h15c.276 0 .5.224.5.5s-.224.5-.5.5z" />
                  </g>
                  <g>
                    <g>
                      <path
                        d="m2.5 22c-.131 0-.259-.052-.354-.146-.123-.123-.173-.3-.133-.468l1.09-4.625c.021-.09.067-.173.133-.239l14.143-14.143c.565-.566 1.554-.566 2.121 0l2.121 2.121c.283.283.439.66.439 1.061s-.156.778-.439 1.061l-14.142 14.141c-.065.066-.148.112-.239.133l-4.625 1.09c-.038.01-.077.014-.115.014zm1.544-4.873-.872 3.7 3.7-.872 14.042-14.041c.095-.095.146-.22.146-.354 0-.133-.052-.259-.146-.354l-2.121-2.121c-.19-.189-.518-.189-.707 0zm3.081 3.283h.01z"
                      />
                    </g>
                    <g>
                      <path
                        d="m17.889 10.146c-.128 0-.256-.049-.354-.146l-3.535-3.536c-.195-.195-.195-.512 0-.707s.512-.195.707 0l3.536 3.536c.195.195.195.512 0 .707-.098.098-.226.146-.354.146z"
                      />
                    </g>
                  </g>
                </svg>
              </a>

							<a href="{% url 'dreams:delete-room' room.id %}">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>remove</title>
                  <path
                    d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
                  ></path>
                </svg>
              </a>
            </div>
						{% endif %}
          </div>

          <div class="room__box scroll" style='background-color:white'>
            <div class="room__header scroll" style='background-color:white'>
              <div class="room__info" style='background-color:white;'>
								<h3 style='color:black'>{{ room.name }}</h3>
								<span style='color:black'>{{ room.created|timesince }} ago</span>
              </div>
              <div class="room__hosted" style='background-color:white;'>
                <p style='color:black'>Hosted By</p>
								<a style='color:black'href="{% url 'dreams:user-profile' room.host.id %}" class="room__author">
                  <div class="avatar avatar--small">
			  <img src={{ room.host.avatar.url }} />
                  </div>
									<span>@{{ room.host.username }}</span>
                </a>
              </div>
              <!--<div class="room__details">
                Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quasi, tenetur laudantium? Dicta repellendus
                rerum consectetur, voluptatem repudiandae eum ea porro cupiditate provident nulla, deserunt, ab ipsum
                corporis laboriosam deleniti molestias?
							</div>-->
							<span style='color:white; background-color:black'class="room__topics">{{ room.topic }}</span>
            </div>
            <div class="room__conversation" style='background-color:white;'>
              <div class="threads scroll" style='background-color:white'>
							{% for message in room_messages %}
                <div class="thread">
                  <div class="thread__top">
                    <div class="thread__author">
											<a style='color:black'href="{% url 'dreams:user-profile' message.user.id %}" class="thread__authorInfo">
                        <div class="avatar avatar--small">
				<img src={{ message.user.avatar.url }} />
                        </div>
												<span>@{{ message.user.username }}</span>
                      </a>
											<span style='color:black'class="thread__date">{{ message.created|timesince }} ago</span>
                    </div>
										{% if request.user == message.user %}
										<a href="{% url 'dreams:delete-message' message.id %}"></a>
                    <div class="thread__delete">
                      <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                        <title>remove</title>
                        <path
                          d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
                        ></path>
                      </svg>
                    </div>
										{% endif %}
                  </div>
                  <div style='color:black'class="thread__details">
										{{ message.body }}
                  </div>
                </div>
								{% endfor %}
              </div>
            </div>
          </div>
          <div class="room__message">
            <form action="#" method='POST'>
		    {% csrf_token %}
		    <input style='background-color:black; color:white'name="body" placeholder="Write your message here..." />
	    </form>
          </div>
        </div>
        <!-- Room End -->

        <!--   Start -->
        <div class="participants" style='background-color:white;'>
					<h3 class="participants__top">Participants <span style='color:white'>({{ participants.count }}Joined)</span></h3>
          <div class="participants__list scroll">
						{% for user in participants %}
						<a href="{% url 'dreams:user-profile' user.id %}" class="participant">
              <div class="avatar avatar--medium">
                <img src="https://randomuser.me/api/portraits/men/37.jpg" />
              </div>
              <p style='color:black'>
							{{ user.username }}
							 <span style='color:black'>@{{ user.username }}</span>
              </p>
            </a>
						{% endfor %}
          </div>
        </div>
        <!--  End -->
      </div>
    </main>
    <script src="script.js"></script>
		{% endblock content %}